id: P78497257
initial_creation_type: input
source_metadata:
  Title: Satyasiddhi Śastra
  Editor: Baroda, B. J. Sandesara.
  Publisher: Oriental Institute
  Place of Publication: Baroda
  Year: '1975'
  1 atha prasthānaskandhaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2008'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  2 atha duḥkhasatyaskandhaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2008'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  3 atha samudayasatyaskandhaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2008'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  4 atha nirodhasatyaskandhaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2008'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  5 atha mārgasatyaskandhaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2008'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
created_at: '2022-03-08T16:51:46.863556'
last_modified_at: '2022-03-08T16:51:46.863564'
